# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sorimjangddol/termhome/practice_Geant4_1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sorimjangddol/termhome/practice_Geant4_1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sorimjangddol/termhome/practice_Geant4_1/CMakeFiles /home/sorimjangddol/termhome/practice_Geant4_1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sorimjangddol/termhome/practice_Geant4_1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Prac

# Build rule for target.
Prac: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Prac
.PHONY : Prac

# fast build rule for target.
Prac/fast:
	$(MAKE) -f CMakeFiles/Prac.dir/build.make CMakeFiles/Prac.dir/build
.PHONY : Prac/fast

#=============================================================================
# Target rules for targets named practice

# Build rule for target.
practice: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 practice
.PHONY : practice

# fast build rule for target.
practice/fast:
	$(MAKE) -f CMakeFiles/practice.dir/build.make CMakeFiles/practice.dir/build
.PHONY : practice/fast

practice.o: practice.cc.o

.PHONY : practice.o

# target to build an object file
practice.cc.o:
	$(MAKE) -f CMakeFiles/practice.dir/build.make CMakeFiles/practice.dir/practice.cc.o
.PHONY : practice.cc.o

practice.i: practice.cc.i

.PHONY : practice.i

# target to preprocess a source file
practice.cc.i:
	$(MAKE) -f CMakeFiles/practice.dir/build.make CMakeFiles/practice.dir/practice.cc.i
.PHONY : practice.cc.i

practice.s: practice.cc.s

.PHONY : practice.s

# target to generate assembly for a file
practice.cc.s:
	$(MAKE) -f CMakeFiles/practice.dir/build.make CMakeFiles/practice.dir/practice.cc.s
.PHONY : practice.cc.s

source/PracActionInitialization.o: source/PracActionInitialization.cc.o

.PHONY : source/PracActionInitialization.o

# target to build an object file
source/PracActionInitialization.cc.o:
	$(MAKE) -f CMakeFiles/practice.dir/build.make CMakeFiles/practice.dir/source/PracActionInitialization.cc.o
.PHONY : source/PracActionInitialization.cc.o

source/PracActionInitialization.i: source/PracActionInitialization.cc.i

.PHONY : source/PracActionInitialization.i

# target to preprocess a source file
source/PracActionInitialization.cc.i:
	$(MAKE) -f CMakeFiles/practice.dir/build.make CMakeFiles/practice.dir/source/PracActionInitialization.cc.i
.PHONY : source/PracActionInitialization.cc.i

source/PracActionInitialization.s: source/PracActionInitialization.cc.s

.PHONY : source/PracActionInitialization.s

# target to generate assembly for a file
source/PracActionInitialization.cc.s:
	$(MAKE) -f CMakeFiles/practice.dir/build.make CMakeFiles/practice.dir/source/PracActionInitialization.cc.s
.PHONY : source/PracActionInitialization.cc.s

source/PracDetectorConstruction.o: source/PracDetectorConstruction.cc.o

.PHONY : source/PracDetectorConstruction.o

# target to build an object file
source/PracDetectorConstruction.cc.o:
	$(MAKE) -f CMakeFiles/practice.dir/build.make CMakeFiles/practice.dir/source/PracDetectorConstruction.cc.o
.PHONY : source/PracDetectorConstruction.cc.o

source/PracDetectorConstruction.i: source/PracDetectorConstruction.cc.i

.PHONY : source/PracDetectorConstruction.i

# target to preprocess a source file
source/PracDetectorConstruction.cc.i:
	$(MAKE) -f CMakeFiles/practice.dir/build.make CMakeFiles/practice.dir/source/PracDetectorConstruction.cc.i
.PHONY : source/PracDetectorConstruction.cc.i

source/PracDetectorConstruction.s: source/PracDetectorConstruction.cc.s

.PHONY : source/PracDetectorConstruction.s

# target to generate assembly for a file
source/PracDetectorConstruction.cc.s:
	$(MAKE) -f CMakeFiles/practice.dir/build.make CMakeFiles/practice.dir/source/PracDetectorConstruction.cc.s
.PHONY : source/PracDetectorConstruction.cc.s

source/PracEventAction.o: source/PracEventAction.cc.o

.PHONY : source/PracEventAction.o

# target to build an object file
source/PracEventAction.cc.o:
	$(MAKE) -f CMakeFiles/practice.dir/build.make CMakeFiles/practice.dir/source/PracEventAction.cc.o
.PHONY : source/PracEventAction.cc.o

source/PracEventAction.i: source/PracEventAction.cc.i

.PHONY : source/PracEventAction.i

# target to preprocess a source file
source/PracEventAction.cc.i:
	$(MAKE) -f CMakeFiles/practice.dir/build.make CMakeFiles/practice.dir/source/PracEventAction.cc.i
.PHONY : source/PracEventAction.cc.i

source/PracEventAction.s: source/PracEventAction.cc.s

.PHONY : source/PracEventAction.s

# target to generate assembly for a file
source/PracEventAction.cc.s:
	$(MAKE) -f CMakeFiles/practice.dir/build.make CMakeFiles/practice.dir/source/PracEventAction.cc.s
.PHONY : source/PracEventAction.cc.s

source/PracPrimaryGeneratorAction.o: source/PracPrimaryGeneratorAction.cc.o

.PHONY : source/PracPrimaryGeneratorAction.o

# target to build an object file
source/PracPrimaryGeneratorAction.cc.o:
	$(MAKE) -f CMakeFiles/practice.dir/build.make CMakeFiles/practice.dir/source/PracPrimaryGeneratorAction.cc.o
.PHONY : source/PracPrimaryGeneratorAction.cc.o

source/PracPrimaryGeneratorAction.i: source/PracPrimaryGeneratorAction.cc.i

.PHONY : source/PracPrimaryGeneratorAction.i

# target to preprocess a source file
source/PracPrimaryGeneratorAction.cc.i:
	$(MAKE) -f CMakeFiles/practice.dir/build.make CMakeFiles/practice.dir/source/PracPrimaryGeneratorAction.cc.i
.PHONY : source/PracPrimaryGeneratorAction.cc.i

source/PracPrimaryGeneratorAction.s: source/PracPrimaryGeneratorAction.cc.s

.PHONY : source/PracPrimaryGeneratorAction.s

# target to generate assembly for a file
source/PracPrimaryGeneratorAction.cc.s:
	$(MAKE) -f CMakeFiles/practice.dir/build.make CMakeFiles/practice.dir/source/PracPrimaryGeneratorAction.cc.s
.PHONY : source/PracPrimaryGeneratorAction.cc.s

source/PracRunAction.o: source/PracRunAction.cc.o

.PHONY : source/PracRunAction.o

# target to build an object file
source/PracRunAction.cc.o:
	$(MAKE) -f CMakeFiles/practice.dir/build.make CMakeFiles/practice.dir/source/PracRunAction.cc.o
.PHONY : source/PracRunAction.cc.o

source/PracRunAction.i: source/PracRunAction.cc.i

.PHONY : source/PracRunAction.i

# target to preprocess a source file
source/PracRunAction.cc.i:
	$(MAKE) -f CMakeFiles/practice.dir/build.make CMakeFiles/practice.dir/source/PracRunAction.cc.i
.PHONY : source/PracRunAction.cc.i

source/PracRunAction.s: source/PracRunAction.cc.s

.PHONY : source/PracRunAction.s

# target to generate assembly for a file
source/PracRunAction.cc.s:
	$(MAKE) -f CMakeFiles/practice.dir/build.make CMakeFiles/practice.dir/source/PracRunAction.cc.s
.PHONY : source/PracRunAction.cc.s

source/PracSteppingAction.o: source/PracSteppingAction.cc.o

.PHONY : source/PracSteppingAction.o

# target to build an object file
source/PracSteppingAction.cc.o:
	$(MAKE) -f CMakeFiles/practice.dir/build.make CMakeFiles/practice.dir/source/PracSteppingAction.cc.o
.PHONY : source/PracSteppingAction.cc.o

source/PracSteppingAction.i: source/PracSteppingAction.cc.i

.PHONY : source/PracSteppingAction.i

# target to preprocess a source file
source/PracSteppingAction.cc.i:
	$(MAKE) -f CMakeFiles/practice.dir/build.make CMakeFiles/practice.dir/source/PracSteppingAction.cc.i
.PHONY : source/PracSteppingAction.cc.i

source/PracSteppingAction.s: source/PracSteppingAction.cc.s

.PHONY : source/PracSteppingAction.s

# target to generate assembly for a file
source/PracSteppingAction.cc.s:
	$(MAKE) -f CMakeFiles/practice.dir/build.make CMakeFiles/practice.dir/source/PracSteppingAction.cc.s
.PHONY : source/PracSteppingAction.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Prac"
	@echo "... install/strip"
	@echo "... practice"
	@echo "... practice.o"
	@echo "... practice.i"
	@echo "... practice.s"
	@echo "... source/PracActionInitialization.o"
	@echo "... source/PracActionInitialization.i"
	@echo "... source/PracActionInitialization.s"
	@echo "... source/PracDetectorConstruction.o"
	@echo "... source/PracDetectorConstruction.i"
	@echo "... source/PracDetectorConstruction.s"
	@echo "... source/PracEventAction.o"
	@echo "... source/PracEventAction.i"
	@echo "... source/PracEventAction.s"
	@echo "... source/PracPrimaryGeneratorAction.o"
	@echo "... source/PracPrimaryGeneratorAction.i"
	@echo "... source/PracPrimaryGeneratorAction.s"
	@echo "... source/PracRunAction.o"
	@echo "... source/PracRunAction.i"
	@echo "... source/PracRunAction.s"
	@echo "... source/PracSteppingAction.o"
	@echo "... source/PracSteppingAction.i"
	@echo "... source/PracSteppingAction.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

